### ISSUE TITLE
It is recommended to add case-ignoring

### ISSUE THREAD

**Issue by yilezhu** [EdiWang/Edi.Captcha.AspNetCore#1]
![image](https://user-images.githubusercontent.com/18655233/51583691-acc26380-1f0c-11e9-90bd-1ad76f757cb6.png)
It is suggested to add case-ignoring judgment when making verification code judgment here.
like this:
 var isValid = userInputCaptcha.Equals(HttpContext.Session.GetString(CaptchaCodeSessionName), StringComparison.OrdinalIgnoreCase);

**Comment by EdiWang** [comment]
Thank for your suggesstion @yilezhu 

This will be implemented soon.
