### ISSUE TITLE
Characters outside of image

### ISSUE THREAD

**Issue by mckornafel** [EdiWang/Edi.Captcha.AspNetCore#14]
Hi, 
I've got something like this on attached image. The characters are out of an image rectangle. The version of component is 3.13.1.
![captcha_issue](https://user-images.githubusercontent.com/11795421/198215040-7e443e52-d38b-43ea-a007-9195c589324f.png)

The code is like that: 
`var s = _captcha.GenerateCaptchaImageFileStream(
                HttpContext.Session,
                330,
                100
                );
            return s;`

Is it a bug or wrong implementation?

Michael K.

**Comment by jamezamm** [comment]
Any feedback on this? I am experiencing the same issue. 

I also noted that the code is always generated top left corner, no matter the size of the image(ImageHeight & ImageWidth). Would be great to have it centered.

**Comment by EdiWang** [comment]
Sorry for late reply, this is a bug I am going to look into it.

**Comment by EdiWang** [comment]
This should be improved in latest package v3.20.0
