### ISSUE TITLE
The sample app can not run in docker container

### ISSUE THREAD

**Issue by bigeagleqd** [EdiWang/Edi.Captcha.AspNetCore#2]
I have an issue when I deploy the sample app in a ubuntu docker container, the exception is can not find 'libdl'.

**Comment by EdiWang** [comment]
@bigeagleqd could you provide detailed ubuntu version and docker configuration information? Thanks

**Comment by EdiWang** [comment]
@bigeagleqd you may look at https://github.com/aspnet/aspnet-docker/issues/95 there is a solution.

**Comment by EdiWang** [comment]
Closed due to longtime inactivity.

**Comment by doghappy** [comment]
same solution (specific) [dotnet/dotnet-docker/issues/618](https://github.com/dotnet/dotnet-docker/issues/618)
