### ISSUE TITLE
在netcore2.2/centos7下使用有什么注意事项吗？

### ISSUE THREAD

**Issue by madeinchinalmc** [EdiWang/Edi.Captcha.AspNetCore#5]
我在win10下面运行我的asp.net core 2.2 mvc网站可以正常使用验证码，我部署到centos7上以后获取验证码接口就报错了，请问下有什么注意事项吗？ 万分感谢~
![image](https://user-images.githubusercontent.com/22071617/70705151-73563a80-1d0e-11ea-84d1-10385d5e0754.png)

**Comment by EdiWang** [comment]
@madeinchinalmc please refer to https://github.com/EdiWang/Edi.Captcha.AspNetCore/issues/2

You may need to install additional packages under Linux to support System.Drawing.Common, regarding https://github.com/dotnet/dotnet-docker/issues/618

**Comment by madeinchinalmc** [comment]
thanks. other, Is it not standard to use Chinese

**Comment by EdiWang** [comment]
@madeinchinalmc NP. It's not standard, I prefer to use Chinese on local platforms like Weibo and WeChat. GitHub is for international communities, English would be better for people to search for issues.
